#!/bin/bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

for f in stim/raw/*.wma; do
	listnum=$(echo $f | sed -e 's/[^0-9]//g')
	f_new="stim/wav/list_${listnum}.wav"
	echo "Converting ${f} to ${f_new}"
	ffmpeg -i "$f" "$f_new"
done
